### ISSUE TITLE
Feature Request: choose alternative output dir

### ISSUE THREAD

**Issue by Ablesius** [hamvocke/dkb2homebank#9]
Hi Ham,

I'd like to add an option `--output-dir` or even `--output-file` with which I can choose where the output can be stored. Just using cwd isn't too useful for me. I am trying to build this myself, but I struggle with the unit tests for that. Then I thought, why not just write the file directly to stdout, so that the output can be piped into any file one wants?

What are your thoughts on that? I have some preliminary code, but it's not ready for a commit (though I could commit a WIP version so you can have a look if you like).

**Comment by hamvocke** [comment]
I think both, writing to stdout and passing an output path would be great
options for the script.

I'm happy to help when it comes to testing, do you want to publish your PR
with your current WIP so we can discuss?

Alexander Blesius <notifications@github.com> schrieb am So., 29. März 2020,
08:27:

**Comment by Ablesius** [comment]
@hamvocke tests pass right now, but I'm not sure this is a good implementation. Also I'd like to add tests for things like "invalid output".

**Comment by hamvocke** [comment]
Closed with #10
